### ISSUE TITLE
`ComposeView` and `IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component`

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#1001]
Update: we've found other, simpler recipes. `AndroidView` is not in the chain, dialog windows always are. More deets in comment.

We have a family of crashes that pass through the following points. (I'll post a complete stack trace in a follow on comment.)

```
IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
  SavedStateRegistry.consumeRestoredStateForKey
  AndroidComposeView.setOnViewTreeOwnersAvailable
  LifecycleRegistry.moveToState
  LifecycleRegistry.setCurrentState
  RealWorkflowLifecycleOwner.updateLifecycle
```

Very hard to reproduce. 

- There's a variant in production that looks like it's related to config change, can't repro
- There's one I can make happen on demand via an espresso test that fires a deep link intent from a notification -- relaunches the activity with the UI pointed to a specific screen. (Can't repro by firing the same intent from adb.)

In both cases, the common elements seem to be that we're building the UI for the first time in a new activity, and that `AndroidView {}` is involved. Debugger reveals a missing call to `SavedStateRegistry.consumeRestoredStateForKey`.

Version info:

```
  lifecycleVersion = '2.5.1'

  composeRuntimeVersion = '1.4.3'
  composeFoundationVersion = '1.4.3'
  composeUiVersion = '1.4.3'
  composeAnimationVersion = '1.4.3'
  composeMaterialVersion = '1.1.0-rc01'

  kotlinVersion = getGradleProperty('square.kotlinVersion', '1.8.10')
  composeCompilerVersion = getGradleProperty('square.composeCompilerVersion', '1.4.4')
```

**Comment by rjrjr** [comment]
Here's the config change variant, first bullet above. I believe every frame here is open source, either Androidx or Workflow.

```
java.lang.IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
        at androidx.savedstate.SavedStateRegistry.consumeRestoredStateForKey(SavedStateRegistry.kt:72)
        at androidx.compose.ui.platform.DisposableSaveableStateRegistry_androidKt.DisposableSaveableStateRegistry(DisposableSaveableStateRegistry.android.kt:75)
        at androidx.compose.ui.platform.DisposableSaveableStateRegistry_androidKt.DisposableSaveableStateRegistry(DisposableSaveableStateRegistry.android.kt:54)
        at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:105)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3248)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3238)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3238)
        at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3173)
        at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:950)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
        at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1060)
        at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
        at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
        at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:121)
        at com.squareup.workflow1.ui.androidx.RealWorkflowLifecycleOwner.updateLifecycle$wf1_core_android(WorkflowLifecycleOwner.kt:203)
        at com.squareup.workflow1.ui.androidx.RealWorkflowLifecycleOwner.updateLifecycle$wf1_core_android$default(WorkflowLifecycleOwner.kt:193)
        at com.squareup.workflow1.ui.androidx.RealWorkflowLifecycleOwner.onStateChanged(WorkflowLifecycleOwner.kt:175)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
        at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:121)
        at com.squareup.workflow1.ui.androidx.RealWorkflowLifecycleOwner.updateLifecycle$wf1_core_android(WorkflowLifecycleOwner.kt:203)
        at com.squareup.workflow1.ui.androidx.RealWorkflowLifecycleOwner.updateLifecycle$wf1_core_android$default(WorkflowLifecycleOwner.kt:193)
        at com.squareup.workflow1.ui.androidx.RealWorkflowLifecycleOwner.onStateChanged(WorkflowLifecycleOwner.kt:175)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
        at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:121)
        at com.squareup.workflow1.ui.androidx.RealWorkflowLifecycleOwner.updateLifecycle$wf1_core_android(WorkflowLifecycleOwner.kt:203)
        at com.squareup.workflow1.ui.androidx.RealWorkflowLifecycleOwner.updateLifecycle$wf1_core_android$default(WorkflowLifecycleOwner.kt:193)
        at com.squareup.workflow1.ui.androidx.RealWorkflowLifecycleOwner.onStateChanged(WorkflowLifecycleOwner.kt:175)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
        at com.squareup.workflow1.ui.androidx.RealWorkflowLifecycleOwner.onViewAttachedToWindow(WorkflowLifecycleOwner.kt:161)
        at android.view.View.dispatchAttachedToWindow(View.java:15544)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1530)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6351)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by rjrjr** [comment]
Fixed one variant (not the one whose stack trace is above) by eliminating a spot where we were driving a `WorkflowViewStub` via an observable stream. Replaced that with direct calls to `ScreenViewHolder.show`. 

Absolutely no idea why that fixed anything, but at least we're getting an idea of what to wiggle.

**Comment by rjrjr** [comment]
> Fixed one variant

False.

**Comment by rjrjr** [comment]
Found this comment in `DisposableSaveableStateRegistry`, while debugging where the {{SaveableStateRegistry:-1}} key comes from (the key that causes the exception to be thrown from {{SavedStateRegistry}}, and thank you androidx team for a characteristically useless exception message):

{code}
    // The view id of AbstractComposeView is used as a key for SavedStateRegistryOwner. If there
    // are multiple AbstractComposeViews in the same Activity/Fragment with the same id(or with
    // no id) this means only the first view will restore its state. There is also an internal
    // mechanism to provide such id not as an Int to avoid ids collisions via view's tag. This
    // api is currently internal to compose:ui, we will see in the future if we need to make a
    // new public api for that use case.
{code}

Sure enough, if I provide generated (and therefore useless) ids for each `ComposeView` we instantiate, the crash goes away. This also breaks view persistence for Compose, but we're pratically there already.

**Comment by rjrjr** [comment]
Do we need to introduce a `WorkflowSavedStateRegistryAggregator` at every `ComposeView` boundary?

**Comment by rjrjr** [comment]
Non-conflicting id's "fix" only worked once. How?

**Comment by rjrjr** [comment]
More likely I'm punchy and missed a step in the repro recipe.

**Comment by rjrjr** [comment]
Possible fix! https://github.com/square/workflow-kotlin/pull/1003. Running it against our internal test suite now.
