### ISSUE TITLE
samples:hello-workflow-fragment:connectedDebugAndroidTest is flaky on api 21

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#568]
```
> Task :samples:hello-workflow-fragment:connectedDebugAndroidTest
Starting 1 tests on test(AVD) - 5.0.2

com.squareup.sample.helloworkflowfragment.HelloWorkflowFragmentAppTest > togglesHelloAndGoodbye[test(AVD) - 5.0.2] FAILED 
	java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.activity.result.contract.ActivityResultContract$SynchronousResult androidx.activity.result.contract.ActivityResultContract.getSynchronousResult(android.content.Context, java.lang.Object)' on a null object reference
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:157)
[InstrumentationResultParser]: Ignoring repeated failed event for com.squareup.sample.helloworkflowfragment.HelloWorkflowFragmentAppTest#togglesHelloAndGoodbye. Stack: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.squareup.sample.helloworkflowfragment/com.squareup.sample.helloworkflowfragment.HelloWorkflowFragmentActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.activity.result.contract.ActivityResultContract$SynchronousResult androidx.activity.result.contract.ActivityResultContract.getSynchronousResult(android.content.Context, java.lang.Object)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.activity.result.contract.ActivityResultContract$SynchronousResult androidx.activity.result.contract.ActivityResultContract.getSynchronousResult(android.content.Context, java.lang.Object)' on a null object reference
at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:157)
at androidx.activity.OnBackPressedDispatcher$LifecycleOnBackPressedCancellable.onStateChanged(OnBackPressedDispatcher.java:233)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
at androidx.fragment.app.Fragment.performStart(Fragment.java:3026)
at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:723)
at android.app.Activity.performStart(Activity.java:5953)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
... 10 more

Tests on test(AVD) - 5.0.2 failed: Instrumentation run failed due to 'java.lang.NullPointerException'
```

**Comment by rjrjr** [comment]
It's gone from flaky to always failing. #582
